name: get-data-from-api
triggers:
  # timer / hook / task / none
  - type: timer
    options:
      period: 6
dictionary:
  token: example-token
inputs:
  - app: api
    options:
      url: http://127.0.0.1:4983/api/examples/fruit
      headers:
        - name: Authorization
          value: "$.token"
    mapper:
      fruit: "#.fruit"
    inputs: []
  - app: api 
    options:
      url: http://127.0.0.1:4983/api/examples/weight
      headers:
        - name: Authorization
          value: "$.token"
    mapper:
      weight: "#"
conditions:
    # and / or / eq / ne / gt / lt / ge / le / contains / exist / javascript
  - operator: and
    conditions:
      - operator: eq
        values:
          - type: variable
            value: "fruit"
          - type: constant
            value: "apple"
      - operator: contains
        values:
          - "$.weight"
          - 10
outputs:
  - app: api
    options:
      url: http://127.0.0.1:4983/api/examples/submit
      method: POST
      headers:
        - name: Authorization
          value: "$.token"
      params:
        thing: "$.fruit"
