name: get-data-from-api-simple
type: simple
triggers:
  # timer / hook / task / none
  - type: timer
    options:
      period: 60
dictionary:
  token: example-token
inputs:
  - app: api
    options:
      url: http://127.0.0.1:4983/api/examples/fruit
      headers:
        - name: Authorization
          value: "$.token"
    conditions:
      - operator: eq
        values:
          - "$.fruit"
          - "apple"
  - app: api
    options:
      url: http://127.0.0.1:4983/api/examples/weight
      headers:
        - name: Authorization
          value: "$.token"
    conditions:
      - operator: contains
        values:
          - "$.data"
          - 10
outputs:
  - app: api
    options:
      url: http://127.0.0.1:4983/api/test
      method: POST
      headers:
        - name: Authorization
          value: "$.token"
      json:
        message: ok
