name: get-data-from-api-simple

dictionary:
  token: example-token

triggers:
  # timer / hook / task / none
  - type: timer
    options:
      period: 10

inputs:
  - app: api
    options:
      url: http://127.0.0.1:4983/api/examples/fruit
      headers:
        - name: Authorization
          value: "${Token {{.token}}}"
    conditions:
      - operator: gt
        values:
          - "$.fruit"
          - "apple"
  - app: api
    options:
      url: http://127.0.0.1:4983/api/examples/weight
      headers:
        - name: Authorization
          value: "${Token {{.token}}}"
    conditions:
      - operator: contains
        values:
          - "$.__app__"
          - 10

outputs:
  - app: api
    options:
      url: http://127.0.0.1:4983/api/examples/submit
      method: POST
      headers:
        - name: Authorization
          value: "${Token {{.token}}}"
      params:
        message: ok
