kind: task
name: get-data-from-api

dictionary:
  token: example-token

triggers:
  # timer / hook / task / none
  - type: timer
    options:
      period: 6

inputs:
  - app: api
    options:
      url: http://127.0.0.1:4983/api/examples/fruit
      headers:
        - name: Authorization
          value:
            type: template
            value: "Token {{.token}}"
    mapper:
      fruit: "$.fruit"
    dependencies: []
  - app: api 
    options:
      url: http://127.0.0.1:4983/api/examples/weight
      headers:
        - name: Authorization
          value: "${Token {{.token}}}"
    mapper:
      weight: "#"
conditions:
    # and / or / eq / ne / gt / lt / ge / le / contains / exist / javascript
  - operator: and
    values:
      - operator: eq
        values:
          - type: variable
            value: "fruit"
          - type: constant
            value: "apple"
      - operator: contains
        values:
          - "$.weight"
          - 10

outputs:
  - app: api
    options:
      url: http://127.0.0.1:4983/api/examples/submit
      method: POST
      headers:
        - name: Authorization
          value: "${Token {{.token}}}"
      params:
        thing: "$.fruit"
