name: get-data-from-api
triggers:
  # timer / hook / task / none
  - type: timer
    options:
      period: 60
dictionary:
  token: example-token
inputs:
  - app: api
    options:
      url: http://127.0.0.1:4983/api/examples/fruit
      headers:
        - name: Authorization
          value: "$.token"
    dictionary:
      fruit: "$.content"
    inputs: []
  - app: API
    options:
      url: http://127.0.0.1:4983/api/examples/weight
      headers:
        - name: Authorization
          value: "$.token"
    dictionary:
      weight: "$.data"
conditions:
    # and / or
  - operator: and
    # eq / ne / gt / lt / ge / le / contains / javascript
    comparator: eq
    values:
      - type: variable
        value: "fruit"
      - type: constant
        value: "apple"
    conditions: []
  - operator: and
    comparator: contains
    values:
      - "$.weight"
      - 10
outputs:
  - app: api
    options:
      url: http://127.0.0.1:4983/api/test
      method: POST
      headers:
        - name: Authorization
          value: "$.token"
      json:
        thing: fruit
      # template: '{"thing":"{{fruit}}"}'