# Should start with --custom-app examples/apps/fetch-and-submit.yaml
kind: task
name: custom-app

dictionary:
  token: example-token

triggers:
  - type: timer
    options:
      period: 3

inputs:
  - app: simple
    mapper:
      content:
        type: variable
        value: "content"

outputs:
  - app: fetch-and-submit
    options:
      token: "$.token"
      content: "$.content"
  - app: print
    options:
      content: "$.data"
