kind: task
name: each-app-example

dictionary:
  list: ["apple", "banana", "orange"]
  map:
    k1: apple
    k2: banana
    k3: orange

triggers:
  - type: timer
    options:
      period: 3

inputs: []

outputs:
  - app: each
    options:
      collection: "$.list"
      steps:
        - app: print
          options:
            content: "$.__value__"
  - app: each
    options:
      collection: "$.map"
      steps:
        - app: print
          options:
            content: "${{{.__key__}}:{{.__value__}}}"
