name: simple-hook

triggers:
  # will add http handler with url /namespaces/${namespace}/tasks/${taskName}/hooks/${hookName}
  - type: hook
    options:
      name: example
      mapper:
        data: "#"

inputs: []
outputs:
  - app: simple
    options:
      content: "$.data"
