name: simple-task-example

dictionary:
  date: "$date"
  token: simple-token

triggers:
  - type: timer
    options:
      period: 3

inputs:
  - app: simple
    mapper:
      content:
        type: variable
        value: "content"

  - app: simple
    mapper:
      content:
        type: variable
        value: "content"

    conditions:
      - operator: eq
        values:
          - "$.content"
          - "apple"

outputs:
  - app: simple
    options:
      content: "$.content"
  - app: simple
    options:
      content: "$.token"
  - app: simple
    options:
      content: "$.date"
  - app: simple
    options:
      content: "$time"
