name: simple-task-example

dictionary:
  content: ""

triggers:
  - type: Timer
    period: 30

inputs:
  - app: Simple
    mapper:
      fruit: "$.content"

outputs:
  - app: Simple
    content: fruit
