name: simple-task-example

dictionary:
  token: simple-token
triggers:
  - type: timer
    options:
      period: 3

inputs:
  - app: simple
    mapper:
      content: "#.content"

    conditions:
      - operator: eq
        values:
          - "#.content"
          - "apple"

outputs:
  - app: simple
    options:
      content: "$.content"
  - app: simple
    options:
      content: "$.token"
