name: simple-task-example

triggers:
  - type: timer
    options:
      period: 10

inputs:
  - app: simple
    conditions:
      - operator: eq
        values:
          - "$.content"
          - "apple"

outputs:
  - app: simple
    options:
      content: ok
